stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/Raigulkim/My project:latest

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    # Добавьте команды для развертывания
